FROM ubuntu

RUN apt-get update
RUN apt-get install -y wget
RUN wget https://github.com/prometheus/snmp_exporter/releases/download/v0.23.0/snmp_exporter-0.23.0.linux-amd64.tar.gz
RUN tar -xzf snmp_exporter-0.23.0.linux-amd64.tar.gz
WORKDIR /snmp_exporter-0.23.0.linux-amd64
CMD ./snmp_exporter