global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
#   - "/Users/root1/Documents/project/prometheus/ex1/alert.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: 'snmp-exporter'
    static_configs:
      - targets:
        - 192.168.0.200
    metrics_path: /snmp
    params:
      module: [cisco]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116